services:
  postgres:
    image: postgres
    ports:
    - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  # appserver:
  #   container_name: server
  #   hostname: localhost
  #   image: basic-spring
  #   build:
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
    
# services:
#   appserver:
#     container_name: server
#     hostname: localhost
#     image: basic-spring
#     ports:
#     - "8080:8080"
#   postgres:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=1234
#     ports:
#     - 5432:5432
#     volumes:
#       - ./postgresdata:/var/lib/postgresql/data
#     privileged: true